
# src/pyhako_cli/strings.py

_CURRENT_LANG = 'en'

STRINGS = {
    'en': {
        "tos_title": "=== Terms of Service ===",
        "tos_warn": "\n[WARNING] Accessing the API via unauthorized means may violate the Terms of Service.\nThis tool is for educational purposes only. Use at your own risk.\n\nOfficial Terms of Service: {}\n\nUser must agree to the following terms (excerpt):\n\n[Japanese Original]\n第3条（知的財産権）\n3. 当社が別に定める場合を除き、お客様が本コンテンツを複製、翻案、頒布、公衆送信等することは禁止します。\n\n第8条（禁止事項）\n(16) 当社が指定するアクセス方法以外の手段で本サービスにアクセスし、またはアクセスを試みる行為\n(17) 自動化された手段（クローラおよび類似の技術を含む）を用いて本サービスにアクセスし、またはアクセスを試みる行為\n\n------------------------\n[Translation (Reference Only)]\n* The Japanese version is authoritative.\n\nArticle 3 (Intellectual Property Rights)\n3. Except where otherwise provided by the Company, the Customer is prohibited from reproducing, adapting, distributing, or publicly transmitting this Content.\n\nArticle 8 (Prohibited Acts)\n(16) Acts of accessing or attempting to access this Service by means other than the access methods designated by the Company.\n(17) Acts of accessing or attempting to access this Service using automated means (including crawlers and similar technologies).",
        "tos_prompt": "\nDo you agree to the above Terms of Service? [y/N]: ",
        "tos_declined": "Terms of Service declined. Exiting.",
        "mode_selection": "\nSelect Mode:\n[1] Message App Backup (Subscription Required)\n[2] Official Blog Backup (Free)\n> ",
        "blog_fetching_members": "Fetching member list from official site...",
        "blog_select_members": "\nAvailable Members:",
        "blog_id_prompt": "\nEnter member IDs (comma-separated, blank for all) > ",
        "blog_scanning": "Scanning blogs...",
        "blog_downloading": "Downloading blogs...",
        "blog_start": "Starting Blog Backup for member: {} (ID: {})",
        "blog_saved": "Saved: {} ({})",
        "interactive_title": "\n=== PyHako CLI Interactive Setup ===\n",
        "cleanup_title": "=== Cleanup Wizard ===",
        "cleanup_warn": "This will remove:\n1. Secure tokens (from system keyring)\n2. Browser session (auth_data directory)\n3. Configuration files (config_*.json)",
        "cleanup_linux_chrome": "4. (Optional) Google Chrome if it was installed by this tool",
        "cleanup_confirm": "\nAre you sure you want to proceed? [y/N]: ",
        "cleanup_aborted": "Aborted.",
        "cleanup_removing": "\nRemoving local files...",
        "cleanup_removed": "Removed {}",
        "cleanup_fail": "Failed to remove {}: {}",
        "cleanup_done": "\nCleanup complete!",
        "cleanup_safe_note": "Note: Your downloaded data in '{}' was KEPT safe.\n    If you want to remove it, please delete the folder manually.",
        "cleanup_linux_chrome_cmd": "\n" + "==================================================" + "\nIf Chrome was installed by this tool and you want to remove it:\n    sudo apt remove google-chrome-stable",

        "setup_title": "=== {} Scraper Setup ===",
        "setup_browser": "Opening browser for login...",
        "setup_auth_dir": "Using persistent auth directory: {}",
        "setup_chrome_not_found": "Chrome not found.",
        "setup_install_chrome": "Installing Chrome... (This may take a moment)",
        "setup_chrome_success": "Chrome installed! Retrying login...",
        "setup_chrome_fail": "Failed to install Chrome: {}",
        "setup_manual_linux": "Please install Chrome manually: sudo apt install google-chrome-stable",
        "setup_manual_other": "Please install Google Chrome from: https://www.google.com/chrome/",
        "setup_login_success": "Config saved!",
        "setup_login_fail": "Login failed.",

        "run_no_config": "No configuration found. Starting setup wizard...",
        "run_setup_fail": "Setup failed or cancelled.",
        "run_init": "Initializing client...",
        "run_auth_expired": "Auth invalid or expired. Starting setup wizard...",
        "run_auth_fail_post_setup": "Auth check failed even after setup.",
        "run_auth_verified": "Auth verified.",
        "run_no_groups": "No groups found.",
        "run_phase_1": "\nPhase 1: Discovering members...",
        "run_found_timelines": "Found {} timelines.\n",
        "run_phase_2": "Phase 2: Collecting Metadata (Parallel)...",
        "run_phase_3": "\nPhase 3: Downloading Media ({} files)...",
        "run_done": "\nDone!",
        "run_output": "Output directory: {}",
        "run_error": "Run error: {}",
        "run_fatal": "\nFatal error: {}",
        "run_interrupted": "\nInterrupted.",

        "interactive_title": "=== Interactive Mode ===",
        "interactive_lang": "Select Language:\n[1] English\n[2] 日本語\n[3] 繁體中文\n[4] 简体中文\n[5] 廣東話\nEnter choice (default: 1): ",
        "interactive_service": "Select Service:\n[1] Nogizaka46\n[2] Sakurazaka46\n[3] Hinatazaka46\nEnter choice (default: 1): ",
        "interactive_out": "Enter output directory (default: {}): ",
        "interactive_offline": "Include past/expired subscriptions? [y/N]: ",
        "interactive_group_id": "Enter Group ID (leave empty to scan all): ",
        "interactive_end": "========================",
        "interactive_exit": "\nPress Enter to exit...",

        "invalid_group_id": "Invalid Group ID, ignoring.",
        "error_keyring_required": "A keyring backend is required (e.g., 'gnome-keyring' on Linux).",
        "error_secure_storage": "Failed to access secure storage: {}",
        "cleanup_secure_fail": "Failed to clear secure tokens: {}",
        
        "help_desc": "PyHako CLI - Sakamichi Series Media Scraper",
        "help_service": "Target Service (Group)",
        "help_output": "Output directory for downloaded content",
        "help_interactive": "Run in interactive wizard mode",
        "help_offline": "Include unsubscribed/past members",
        "help_group": "Filter by Group ID",
        "help_members": "Filter by Member IDs",
        "help_cleanup": "Remove auth data and config files",
        "help_lang": "Language (en, ja, zh-TW, zh-CN, yue)",
        "help_verbose": "Enable verbose logging"
    },
    'ja': {
        "tos_title": "=== 利用規約 ===",
        "tos_warn": "\n【警告】正規以外の手段でのAPIアクセスは利用規約に違反する可能性があります。\n本ツールは教育目的のみで提供されています。自己責任でご利用ください。\n\n公式利用規約: {}\n\n本ツールを使用するには、以下の公式規約（抜粋）に同意する必要があります：\n\n第3条（知的財産権）\n3. 当社が別に定める場合を除き、お客様が本コンテンツを複製、翻案、頒布、公衆送信等することは禁止します。\n\n第8条（禁止事項）\n(16) 当社が指定するアクセス方法以外の手段で本サービスにアクセスし、またはアクセスを試みる行為\n(17) 自動化された手段（クローラおよび類似の技術を含む）を用いて本サービスにアクセスし、またはアクセスを試みる行為",
        "tos_prompt": "\n上記の利用規約に同意しますか？ [y/N]: ",
        "tos_declined": "同意されませんでした。終了します。",
        "mode_selection": "\nモードを選択:\n[1] メッセージアプリ バックアップ (要購読)\n[2] 公式ブログ バックアップ (無料)\n> ",
        "blog_fetching_members": "公式サイトからメンバーリストを取得中...",
        "blog_select_members": "\n利用可能なメンバー:",
        "blog_id_prompt": "\nメンバーIDを入力 (カンマ区切り、空白で全員) > ",
        "blog_scanning": "ブログをスキャン中...",
        "blog_downloading": "ブログをダウンロード中...",
        "blog_start": "ブログバックアップを開始: {} (ID: {})",
        "blog_saved": "保存完了: {} ({})",

        "cleanup_title": "=== クリーンアップウィザード ===",
        "cleanup_warn": "以下の項目が削除されます：\n1. セキュアトークン (システムキーリング)\n2. ブラウザセッション (auth_data ディレクトリ)\n3. 設定ファイル (config_*.json)",
        "cleanup_linux_chrome": "4. (任意) Google Chrome (このツールでインストールされた場合)",
        "cleanup_confirm": "\n続行しますか？ [y/N]: ",
        "cleanup_aborted": "中止しました。",
        "cleanup_removing": "\nローカルファイルを削除しています...",
        "cleanup_removed": "削除しました: {}",
        "cleanup_fail": "削除に失敗しました {}: {}",
        "cleanup_done": "\nクリーンアップ完了！",
        "cleanup_safe_note": "注意: '{}' にダウンロードされたデータは保持されています。\n    削除する場合は、フォルダを手動で削除してください。",
        "cleanup_linux_chrome_cmd": "\n" + "==================================================" + "\nこのツールでChromeをインストールし、それを削除したい場合：\n    sudo apt remove google-chrome-stable",

        "setup_title": "=== {} スクレイパー設定 ===",
        "setup_browser": "ログインのためにブラウザを開いています...",
        "setup_auth_dir": "認証ディレクトリを使用中: {}",
        "setup_chrome_not_found": "Chromeが見つかりません。",
        "setup_install_chrome": "Chromeをインストール中... (これには時間がかかる場合があります)",
        "setup_chrome_success": "Chromeのインストールに成功！ログインを再試行します...",
        "setup_chrome_fail": "Chromeのインストールに失敗: {}",
        "setup_manual_linux": "Chromeを手動でインストールしてください: sudo apt install google-chrome-stable",
        "setup_manual_other": "次のURLからGoogle Chromeをインストールしてください: https://www.google.com/chrome/",
        "setup_login_success": "設定を保存しました！",
        "setup_login_fail": "ログインに失敗しました。",

        "run_no_config": "設定が見つかりません。セットアップウィザードを開始します...",
        "run_setup_fail": "セットアップが失敗したか、キャンセルされました。",
        "run_init": "クライアントを初期化中...",
        "run_auth_expired": "認証が無効または期限切れです。セットアップウィザードを開始します...",
        "run_auth_fail_post_setup": "セットアップ後も認証チェックに失敗しました。",
        "run_auth_verified": "認証確認済み。",
        "run_no_groups": "グループが見つかりません。",
        "run_phase_1": "\nフェーズ 1: メンバーを検索中...",
        "run_found_timelines": "{} 件のタイムラインが見つかりました。\n",
        "run_phase_2": "フェーズ 2: メタデータを収集中 (並列処理)...",
        "run_phase_3": "\nフェーズ 3: メディアをダウンロード中 ({} ファイル)...",
        "run_done": "\n完了！",
        "run_output": "出力ディレクトリ: {}",
        "run_error": "実行エラー: {}",
        "run_fatal": "\n致命的なエラー: {}",
        "run_interrupted": "\n中断されました。",

        "interactive_title": "=== 対話モード ===",
        "interactive_lang": "言語を選択:\n[1] English\n[2] 日本語\n[3] 繁體中文\n[4] 简体中文\n[5] 廣東話\n選択してください (デフォルト: 1): ",
        "interactive_service": "サービスを選択:\n[1] 乃木坂46\n[2] 櫻坂46\n[3] 日向坂46\n選択してください (デフォルト: 1): ",
        "interactive_out": "出力ディレクトリを入力 (デフォルト: {}): ",
        "interactive_offline": "解約済み/過去に購読していたメンバーを含めますか？ [y/N]: ",
        "interactive_group_id": "グループIDを入力 (空欄で全スキャン): ",
        "interactive_end": "========================",
        "interactive_exit": "\nEnterキーを押して終了...",

        "invalid_group_id": "無効なグループIDです。無視します。",
        "error_keyring_required": "キーリングバックエンドが必要です (例: Linuxでは 'gnome-keyring')。",
        "error_secure_storage": "セキュアストレージへのアクセスに失敗しました: {}",
        "cleanup_secure_fail": "セキュアトークンの削除に失敗しました: {}",

        "help_desc": "PyHako CLI - 坂道シリーズ メディアスクレイパー",
        "help_service": "対象サービス (グループ)",
        "help_output": "ダウンロード保存先ディレクトリ",
        "help_interactive": "対話モードで実行",
        "help_offline": "解約/過去のメンバーを含める",
        "help_group": "グループIDでフィルタ",
        "help_members": "メンバーIDでフィルタ",
        "help_cleanup": "認証データと設定を削除",
        "help_lang": "言語 (en, ja, zh-TW, zh-CN, yue)",
        "help_verbose": "詳細ログを有効化"
    },
    'zh-TW': {
        "tos_title": "=== 服務條款 ===",
        "tos_warn": "\n【警告】透過非官方手段存取 API 可能違反服務條款。\n本工具僅供教學用途。請自行承擔風險。\n\n官方服務條款: {}\n\n使用本工具前，您必須同意以下官方條款（節錄）：\n\n[日文原文]\n第3条（知的財産権）\n3. 当社が別に定める場合を除き、お客様が本コンテンツを複製、翻案、頒布、公衆送信等することは禁止します。\n\n第8条（禁止事項）\n(16) 当社が指定するアクセス方法以外の手段で本サービスにアクセスし、またはアクセスを試みる行為\n(17) 自動化された手段（クローラおよび類似の技術を含む）を用いて本サービスにアクセスし、またはアクセスを試みる行為\n\n------------------------\n[翻譯 (僅供參考)]\n* 以日文原文為準\n\n第3條（智慧財產權）\n3. 除本公司另有規定外，禁止客戶對本內容進行複製、改編、散布、公開傳輸等行為。\n\n第8條（禁止事項）\n(16) 透過本公司指定之存取方法以外的手段存取本服務，或嘗試存取本服務的行為。\n(17) 使用自動化手段（包含網路爬蟲及類似技術）存取本服務，或嘗試存取本服務的行為。",
        "tos_prompt": "\n您是否同意上述服務條款？ [y/N]: ",
        "tos_declined": "拒絕服務條款。程式結束。",
        "mode_selection": "\n選擇模式:\n[1] 訊息 App 備份 (需訂閱)\n[2] 官方部落格 備份 (免費)\n> ",
        "blog_fetching_members": "正在從官方網站取得成員列表...",
        "blog_select_members": "\n可選擇的成員:",
        "blog_id_prompt": "\n輸入成員 ID (逗號分隔，空白選擇全部) > ",
        "blog_scanning": "正在掃描部落格...",
        "blog_downloading": "正在下載部落格...",
        "blog_start": "開始備份部落格: {} (ID: {})",
        "blog_saved": "已儲存: {} ({})",

        "cleanup_title": "=== 清除工具精靈 ===",
        "cleanup_warn": "此操作將會移除：\n1. 安全令牌 (系統鑰匙圈)\n2. 瀏覽器工作階段 (auth_data 目錄)\n3. 設定檔 (config_*.json)",
        "cleanup_linux_chrome": "4. (選用) Google Chrome (若是透過此工具安裝)",
        "cleanup_confirm": "\n您確定要繼續嗎？ [y/N]: ",
        "cleanup_aborted": "已中止。",
        "cleanup_removing": "\n正在移除本地檔案...",
        "cleanup_removed": "已移除 {}",
        "cleanup_fail": "無法移除 {}: {}",
        "cleanup_done": "\n清除完成！",
        "cleanup_safe_note": "注意：您下載在 '{}' 的資料已保留。\n    若要移除，請手動刪除該資料夾。",
        "cleanup_linux_chrome_cmd": "\n" + "==================================================" + "\n如果 Chrome 是由本工具安裝且您希望將其移除：\n    請執行 sudo apt remove google-chrome-stable",

        "setup_title": "=== {} 爬蟲設定 ===",
        "setup_browser": "正在開啟瀏覽器以進行登入...",
        "setup_auth_dir": "使用已儲存的驗證目錄：{}",
        "setup_chrome_not_found": "找不到 Chrome。",
        "setup_install_chrome": "正在安裝 Chrome... (這可能需要一點時間)",
        "setup_chrome_success": "Chrome 安裝成功！正在重試登入...",
        "setup_chrome_fail": "Chrome 安裝失敗：{}",
        "setup_manual_linux": "請手動安裝 Chrome：sudo apt install google-chrome-stable",
        "setup_manual_other": "請從此處安裝 Google Chrome：https://www.google.com/chrome/",
        "setup_login_success": "設定已儲存！",
        "setup_login_fail": "登入失敗。",

        "run_no_config": "找不到設定檔。正在啟動設定精靈...",
        "run_setup_fail": "設定失敗或已取消。",
        "run_init": "正在初始化客戶端...",
        "run_auth_expired": "驗證無效或已過期。正在啟動設定精靈...",
        "run_auth_fail_post_setup": "設定後驗證檢查仍然失敗。",
        "run_auth_verified": "驗證成功。",
        "run_no_groups": "找不到群組。",
        "run_phase_1": "\n第一階段：正在搜尋成員...",
        "run_found_timelines": "找到 {} 個時間軸。\n",
        "run_phase_2": "第二階段：正在收集中繼資料 (平行處理)...",
        "run_phase_3": "\n第三階段：正在下載媒體檔案 ({} 個檔案)...",
        "run_done": "\n完成！",
        "run_output": "輸出目錄：{}",
        "run_error": "執行錯誤：{}",
        "run_fatal": "\n嚴重錯誤：{}",
        "run_interrupted": "\n已中斷。",

        "interactive_title": "=== 互動模式 ===",
        "interactive_lang": "選擇語言：\n[1] English\n[2] 日本語\n[3] 繁體中文\n[4] 简体中文\n[5] 廣東話\n請輸入選項 (預設: 1): ",
        "interactive_service": "選擇服務：\n[1] 乃木坂46\n[2] 櫻坂46\n[3] 日向坂46\n請輸入選項 (預設: 1): ",
        "interactive_out": "請輸入輸出目錄 (預設: {}): ",
        "interactive_offline": "包含過往訂閱/已退訂的成員？ [y/N]: ",
        "interactive_group_id": "請輸入群組 ID (留空以掃描全部): ",
        "interactive_end": "========================",
        "interactive_exit": "\n按 Enter 鍵離開...",

        "invalid_group_id": "Group ID 無效，已忽略。",
        "error_keyring_required": "需要 Keyring Backend (例如 Linux 上的 'gnome-keyring')。",
        "error_secure_storage": "無法存取安全儲存區：{}",
        "cleanup_secure_fail": "無法清除安全權杖 (Secure Tokens)：{}",

        "help_desc": "PyHako CLI - 坂道系列媒體爬蟲",
        "help_service": "目標服務 (團體)",
        "help_output": "下載內容輸出目錄",
        "help_interactive": "執行互動式精靈模式",
        "help_offline": "包含已畢業/退訂成員",
        "help_group": "依 Group ID 過濾",
        "help_members": "依 Member IDs 過濾",
        "help_cleanup": "移除驗證資料與設定檔",
        "help_lang": "語言 (en, ja, zh-TW, zh-CN, yue)",
        "help_verbose": "啟用詳細日誌"
    },
    'zh-CN': {
        "tos_title": "=== 服务条款 ===",
        "tos_warn": "\n【警告】通过非官方手段访问 API 可能违反服务条款。\n本工具仅供教学用途。请自行承担风险。\n\n官方服务条款: {}\n\n使用本工具前，您必须同意以下官方条款（节录）：\n\n[日文原文]\n第3条（知的財産権）\n3. 当社が別に定める場合を除き、お客様が本コンテンツを複製、翻案、頒布、公衆送信等することは禁止します。\n\n第8条（禁止事項）\n(16) 当社が指定するアクセス方法以外の手段で本サービスにアクセスし、またはアクセスを試みる行為\n(17) 自動化された手段（クローラおよび類似の技術を含む）を用いて本サービスにアクセスし、またはアクセスを試みる行為\n\n------------------------\n[翻译 (仅供参考)]\n* 以日文原文为准\n\n第3条（知识产权）\n3. 除本公司另有规定外，禁止客户对本内容进行复制、改编、散布、公开传输等行为。\n\n第8条（禁止事项）\n(16) 通过本公司指定之访问方法以外的手段访问本服务，或尝试访问本服务的行为。\n(17) 使用自动化手段（包括网络爬虫及类似技术）访问本服务，或尝试访问本服务的行为。",
        "tos_prompt": "\n您是否同意上述服务条款？ [y/N]: ",
        "tos_declined": "拒绝服务条款。程序退出。",
        "mode_selection": "\n选择模式:\n[1] 消息 App 备份 (需订阅)\n[2] 官方博客 备份 (免费)\n> ",
        "blog_fetching_members": "正在从官方网站获取成员列表...",
        "blog_select_members": "\n可选择的成员:",
        "blog_id_prompt": "\n输入成员 ID (逗号分隔，空白选择全部) > ",
        "blog_scanning": "正在扫描博客...",
        "blog_downloading": "正在下载博客...",
        "blog_start": "开始备份博客: {} (ID: {})",
        "blog_saved": "已保存: {} ({})",

        "cleanup_title": "=== 清理向导 ===",
        "cleanup_warn": "此操作将删除：\n1. 安全令牌 (系统密钥链)\n2. 浏览器会话 (auth_data 目录)\n3. 配置文件 (config_*.json)",
        "cleanup_linux_chrome": "4. (可选) Google Chrome (如果是通过此工具安装的)",
        "cleanup_confirm": "\n您确定要继续吗？ [y/N]: ",
        "cleanup_aborted": "已中止。",
        "cleanup_removing": "\n正在删除本地文件...",
        "cleanup_removed": "已删除 {}",
        "cleanup_fail": "无法删除 {}: {}",
        "cleanup_done": "\n清理完成！",
        "cleanup_safe_note": "注意：您下载在 '{}' 的数据已保留。\n    如果需要删除，请手动删除该文件夹。",
        "cleanup_linux_chrome_cmd": "\n" + "==================================================" + "\n如果 Chrome 是由本工具安装且您希望将其删除：\n    请运行 sudo apt remove google-chrome-stable",

        "setup_title": "=== {} 爬虫设置 ===",
        "setup_browser": "正在打开浏览器以进行登录...",
        "setup_auth_dir": "使用持久化验证目录：{}",
        "setup_chrome_not_found": "未找到 Chrome。",
        "setup_install_chrome": "正在安装 Chrome... (这可能需要一点时间)",
        "setup_chrome_success": "Chrome 安装成功！正在重试登录...",
        "setup_chrome_fail": "Chrome 安装失败：{}",
        "setup_manual_linux": "请手动安装 Chrome：sudo apt install google-chrome-stable",
        "setup_manual_other": "请从此链接安装 Google Chrome：https://www.google.com/chrome/",
        "setup_login_success": "配置已保存！",
        "setup_login_fail": "登录失败。",

        "run_no_config": "未找到配置文件。正在启动设置向导...",
        "run_setup_fail": "设置失败或已取消。",
        "run_init": "正在初始化客户端...",
        "run_auth_expired": "验证无效或已过期。正在启动设置向导...",
        "run_auth_fail_post_setup": "设置后验证检查仍然失败。",
        "run_auth_verified": "验证成功。",
        "run_no_groups": "未找到群组。",
        "run_phase_1": "\n第一阶段：正在发现成员...",
        "run_found_timelines": "找到 {} 条时间轴。\n",
        "run_phase_2": "第二阶段：正在收集元数据 (并行处理)...",
        "run_phase_3": "\n第三阶段：正在下载媒体文件 ({} 个文件)...",
        "run_done": "\n完成！",
        "run_output": "输出目录：{}",
        "run_error": "运行错误：{}",
        "run_fatal": "\n致命错误：{}",
        "run_interrupted": "\n已中断。",

        "interactive_title": "=== 交互模式 ===",
        "interactive_lang": "选择语言：\n[1] English\n[2] 日本語\n[3] 繁體中文\n[4] 简体中文\n[5] 廣東話\n输入选项 (默认: 1): ",
        "interactive_service": "选择服务：\n[1] 乃木坂46\n[2] 樱坂46\n[3] 日向坂46\n输入选项 (默认: 1): ",
        "interactive_out": "输入输出目录 (默认: {}): ",
        "interactive_offline": "包含过往订阅/已退订的成员？ [y/N]: ",
        "interactive_group_id": "输入群组 ID (留空以扫描全部): ",
        "interactive_end": "========================",
        "interactive_exit": "\n按回车键退出...",

        "invalid_group_id": "Group ID 无效，已忽略。",
        "error_keyring_required": "需要 Keyring Backend (例如 Linux 上的 'gnome-keyring')。",
        "error_secure_storage": "无法访问安全存储：{}",
        "cleanup_secure_fail": "无法清除安全令牌：{}",

        "help_desc": "PyHako CLI - 坂道系列媒体爬虫",
        "help_service": "目标服务 (团体)",
        "help_output": "下载内容输出目录",
        "help_interactive": "运行交互式向导模式",
        "help_offline": "包含已毕业/退订成员",
        "help_group": "按 Group ID 过滤",
        "help_members": "按 Member IDs 过滤",
        "help_cleanup": "删除验证数据和配置文件",
        "help_lang": "语言 (en, ja, zh-TW, zh-CN, yue)",
        "help_verbose": "启用详细日志"
    },
    'yue': {
        "tos_title": "=== 服務條款 ===",
        "tos_warn": "\n【警告】用非官方手段 Access 個 API 可能會違反服務條款\n呢個工具係教學用途。風險自負。\n\n官方服務條款: {}\n\n用呢個工具之前，你要同意以下官方條款（節錄）：\n\n[日文原文]\n第3条（知的財産権）\n3. 当社が別に定める場合を除き、お客様が本コンテンツを複製、翻案、頒布、公衆送信等することは禁止します。\n\n第8条（禁止事項）\n(16) 当社が指定するアクセス方法以外の手段で本サービスにアクセスし、またはアクセスを試みる行為\n(17) 自動化された手段（クローラおよび類似の技術を含む）を用いて本サービスにアクセスし、またはアクセスを試みる行為\n\n------------------------\n[翻譯 (參考用)]\n* 一切以日文原文為準\n\n第3條（知識產權）\n3. 除咗本公司另有規定之外，禁止客戶將本內容複製、改編、散布、或者公開傳輸等。\n\n第8條（禁止事項）\n(16) 用本公司指定存取方法以外嘅手段去存取本服務，或者嘗試存取本服務嘅行為。\n(17) 用自動化手段（包括爬蟲同埋類似嘅技術）去存取本服務，或者嘗試存取本服務嘅行為。",
        "tos_prompt": "\n你同唔同意以上服務條款？ [y/N]: ",
        "tos_declined": "拒絕服務條款。Bye Bye。",
        "mode_selection": "\n揀模式:\n[1] 訊息 App 備份 (要訂閱)\n[2] 官方 Blog 備份 (免費)\n> ",
        "blog_fetching_members": "攞緊官方網站嘅成員列表...",
        "blog_select_members": "\n可揀嘅成員:",
        "blog_id_prompt": "\n輸入成員 ID (逗號分開，唔入揀全部) > ",
        "blog_scanning": "掃描緊 Blog...",
        "blog_downloading": "下載緊 Blog...",
        "blog_start": "開始備份 Blog: {} (ID: {})",
        "blog_saved": "儲存咗: {} ({})",

        "cleanup_title": "=== 清理精靈 ===",
        "cleanup_warn": "這將會移除：\n1. 安全令牌 (系統鑰匙圈)\n2. 瀏覽器 Session (auth_data 目錄)\n3. 設定檔 (config_*.json)",
        "cleanup_linux_chrome": "4. (可選) Google Chrome (如果係由呢個工具安裝嘅話)",
        "cleanup_confirm": "\n你係咪確定要繼續？ [y/N]: ",
        "cleanup_aborted": "已中止。",
        "cleanup_removing": "\n移除緊本機檔案...",
        "cleanup_removed": "已移除 {}",
        "cleanup_fail": "移除唔到 {}: {}",
        "cleanup_done": "\n清理完成！",
        "cleanup_safe_note": "註：你下載喺 '{}' 嘅資料已經保留咗。\n    如果你想移除埋，請手動 delete 個 folder。",
        "cleanup_linux_chrome_cmd": "\n" + "==================================================" + "\n如果 Chrome 係由呢個工具安裝而你想移除佢：\n    請執行 sudo apt remove google-chrome-stable",

        "setup_title": "=== {} 爬蟲設定 ===",
        "setup_browser": "打開緊瀏覽器準備登入...",
        "setup_auth_dir": "用緊 Persistent 驗證目錄：{}",
        "setup_chrome_not_found": "搵唔到 Chrome。",
        "setup_install_chrome": "安裝緊 Chrome... (可能要等一陣)",
        "setup_chrome_success": "Chrome 安裝成功！試緊重新登入...",
        "setup_chrome_fail": "安裝唔到 Chrome：{}",
        "setup_manual_linux": "請手動安裝 Chrome：sudo apt install google-chrome-stable",
        "setup_manual_other": "請去呢度安裝 Google Chrome：https://www.google.com/chrome/",
        "setup_login_success": "Config 已儲存！",
        "setup_login_fail": "登入失敗。",

        "run_no_config": "搵唔到設定檔。啟動緊設定精靈...",
        "run_setup_fail": "設定失敗或者取消咗。",
        "run_init": "Client 初始化中...",
        "run_auth_expired": "驗證無效或者過咗期。啟動緊設定精靈...",
        "run_auth_fail_post_setup": "設定完之後驗證依然失敗。",
        "run_auth_verified": "驗證成功。",
        "run_no_groups": "搵唔到群組。",
        "run_phase_1": "\nPhase 1: 搵緊成員...",
        "run_found_timelines": "搵到 {} 個 Timeline。\n",
        "run_phase_2": "Phase 2: 收集緊 Metadata (並行處理)...",
        "run_phase_3": "\nPhase 3: 下載緊媒體檔案 ({} 個檔案)...",
        "run_done": "\n搞掂！",
        "run_output": "輸出目錄：{}",
        "run_error": "執行錯誤：{}",
        "run_fatal": "\n嚴重錯誤：{}",
        "run_interrupted": "\n已中斷。",

        "interactive_title": "=== 互動模式 ===",
        "interactive_lang": "揀語言：\n[1] English\n[2] 日本語\n[3] 繁體中文\n[4] 简体中文\n[5] 廣東話\n請輸入選項 (Default: 1): ",
        "interactive_service": "揀服務：\n[1] 乃木坂46\n[2] 櫻坂46\n[3] 日向坂46\n請輸入選項 (Default: 1): ",
        "interactive_out": "請輸入輸出目錄 (Default: {}): ",
        "interactive_offline": "包唔包以前訂過/退咗訂嘅成員？ [y/N]: ",
        "interactive_group_id": "請輸入 Group ID (留空就 Scan 全部): ",
        "interactive_end": "========================",
        "interactive_exit": "\n撳 Enter 離開...",

        "invalid_group_id": "Group ID 無效，Ignore 咗。",
        "error_keyring_required": "需要 Keyring Backend (例如 Linux 上面要 'gnome-keyring')。",
        "error_secure_storage": "存取唔到安全儲存區：{}",
        "cleanup_secure_fail": "清除唔到安全 Token：{}",

        "help_desc": "PyHako CLI - 坂道系列 Media Scraper",
        "help_service": "目標服務 (Group)",
        "help_output": "下載內容輸出目錄",
        "help_interactive": "用互動式 Wizard 模式",
        "help_offline": "包埋以前訂過/退咗訂嘅成員",
        "help_group": "跟 Group ID 過濾",
        "help_members": "跟 Member IDs 過濾",
        "help_cleanup": "移除驗證資料同 Config",
        "help_lang": "語言 (en, ja, zh-TW, zh-CN, yue)",
        "help_verbose": "開詳細 Log"
    }
}

def set_language(lang: str):
    global _CURRENT_LANG
    _CURRENT_LANG = lang

def get_language() -> str:
    return _CURRENT_LANG

def get_string(key: str) -> str:
    lang_dict = STRINGS.get(_CURRENT_LANG, STRINGS['en'])
    val = lang_dict.get(key)
    if val is None:
        # Fallback to English
        val = STRINGS['en'].get(key, key)
    return val
