
name: Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout PyHakoCLI
      uses: actions/checkout@v4
      with:
        path: PyHakoCLI

    - name: Checkout PyHako (Core)
      uses: actions/checkout@v4
      with:
        repository: xebjhm/PyHako
        path: PyHako

    - name: Install uv
      uses: astral-sh/setup-uv@v5


    - name: Set up Python ${{ matrix.python-version }}
      working-directory: PyHakoCLI
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: PyHakoCLI
      run: uv sync --all-extras --dev

    - name: Run Tests
      working-directory: PyHakoCLI
      run: uv run pytest
